name: Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          gradle-home-cache-includes: |
            caches
            notifications
          gradle-home-cache-cleanup: true
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

      - name: Init secrets
        run: |
          KEYSTORE_FILE_PATH=${{ secrets.KEYSTORE_FILE_PATH }}

          touch .env
          echo "KEYSTORE_FILE_PATH=$KEYSTORE_FILE_PATH" >> .env
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> .env
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> .env
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> .env

          mkdir -p "${KEYSTORE_FILE_PATH%/*}" && touch "$KEYSTORE_FILE_PATH"
          echo "${{ secrets.KEYSTORE_FILE_CONTENT_BASE64_ENCODED }}" | base64 --decode >> $KEYSTORE_FILE_PATH

      - name: Build AAB
        run: ./gradlew bundleRelease --stacktrace

      - name: Release to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}
          packageName: "me.amrbashir.hijriwidget"
          releaseFiles: "app/build/outputs/bundle/release/app-release.aab"
          track: "internal"
          status: draft
          inAppUpdatePriority: 5
          mappingFile: "app/build/outputs/mapping/release/mapping.txt"

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Rename and move APK
        run: mv app/build/outputs/apk/release/app-release.apk hijri-widget-${{ github.ref_name }}.apk

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          name: Hijri Widget ${{ github.ref_name }}
          files: hijri-widget-${{ github.ref_name }}.apk
          generate_release_notes: true
